language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi

script:
  - go test -v ./autoscaling/
  - go test -v ./aws/
  - go test -v ./cloudformation/
  - go test -v ./cloudfront/
  - go test -v ./cloudwatch/
  - go test -v ./dynamodb/
  - go test -v ./ec2/
  - go test -v ./ecs/
  - go test -v ./elb/
  - go test -v ./iam/
  - go test -v ./rds/
  - go test -v ./route53/
  - go test -v ./s3/
  - go test -v ./sqs/
  - go test -v ./sts/
  - go test -v ./exp/mturk/
  - go test -v ./exp/sdb/
  # - go test -v ./exp/ses/
  # - go test -v ./exp/sns/
