package ecs

var CreateClusterResponse = `
<CreateClusterResponse xmlns="http://ecs.amazonaws.com/doc/2014-11-13/">
	<ResponseMetadata>
		<RequestId>8d798a29-f083-11e1-bdfb-cb223EXAMPLE</RequestId>
	</ResponseMetadata>
   <CreateClusterResult>
    <Cluster>
      <ClusterArn>arn:aws:ecs:region:aws_account_id:cluster/default</ClusterArn>
      <ClusterName>default</ClusterName>
      <Status>ACTIVE</Status>
    </Cluster>
  </CreateClusterResult>
</CreateClusterResponse> 
`
var DeregisterContainerInstanceResponse = `
<DeregisterContainerInstanceResponse xmlns="http://ecs.amazonaws.com/doc/2014-11-13/">
  <ResponseMetadata>
    <RequestId>8d798a29-f083-11e1-bdfb-cb223EXAMPLE</RequestId>
  </ResponseMetadata>
   <DeregisterContainerInstanceResult>
    <ContainerInstance>
     <AgentConnected>False</AgentConnected>
     <ContainerInstanceArn>arn:aws:ecs:us-east-1:aws_account_id:container-instance/container_instance_UUID</ContainerInstanceArn>
     <Ec2InstanceId>instance_id</Ec2InstanceId>
     <Status>INACTIVE</Status>
     <RegisteredResources>
        <Resource>
          <IntegerValue>2048</IntegerValue>
          <LongValue>0</LongValue>
          <Type>INTEGER</Type>
          <Name>CPU</Name>
          <DoubleValue>0.0</DoubleValue>
        </Resource>
        <Resource>
          <IntegerValue>3955</IntegerValue>
          <LongValue>0</LongValue>
          <Type>INTEGER</Type>
          <Name>MEMORY</Name>
          <DoubleValue>0.0</DoubleValue>
        </Resource>
        <Resource>
          <IntegerValue>0</IntegerValue>
          <LongValue>0</LongValue>
          <Type>STRINGSET</Type>
          <StringSetValue>
            <member>2376</member>
            <member>22</member>
            <member>51678</member>
            <member>2375</member>
          </StringSetValue>
          <Name>PORTS</Name>
          <DoubleValue>0.0</DoubleValue>
        </Resource>
     </RegisteredResources>
     <RemainingResources>
        <Resource>
          <IntegerValue>2048</IntegerValue>
          <LongValue>0</LongValue>
          <Type>INTEGER</Type>
          <Name>CPU</Name>
          <DoubleValue>0.0</DoubleValue>
        </Resource>
        <Resource>
          <IntegerValue>3955</IntegerValue>
          <LongValue>0</LongValue>
          <Type>INTEGER</Type>
          <Name>MEMORY</Name>
          <DoubleValue>0.0</DoubleValue>
        </Resource>
        <Resource>
          <IntegerValue>0</IntegerValue>
          <LongValue>0</LongValue>
          <Type>STRINGSET</Type>
          <StringSetValue>
            <member>2376</member>
            <member>22</member>
            <member>51678</member>
            <member>2375</member>
          </StringSetValue>
          <Name>PORTS</Name>
          <DoubleValue>0.0</DoubleValue>
        </Resource>
     </RemainingResources>
    </ContainerInstance>
  </DeregisterContainerInstanceResult>
</DeregisterContainerInstanceResponse> 
`
